---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 512
  run_list:
  - recipe[apt]
- name: debian-7.1.0
  driver_config:
    box: opscode-debian-7.1.0
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 512
  run_list:
  - recipe[apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 512
  run_list:
  - recipe[yum::epel]
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          minor: 4
          incremental: 0
    stanchion:
      package:
        version:
          minor: 4
          incremental: 0
    riak_cs_control:
      package:
        version:
          minor: 0
          incremental: 1
    riak:
      cs_version: "1.4.0"
      package:
        version:
          minor: 4
          incremental: 1
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: default13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          minor: 3
          incremental: 2
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          minor: 4
          incremental: 0
    stanchion:
      package:
        version:
          minor: 4
          incremental: 0
    riak_cs_control:
      package:
        version:
          minor: 0
          incremental: 1
    riak:
      cs_version: "1.4.0"
      package:
        version:
          minor: 4
          incremental: 1
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          minor: 3
          incremental: 2
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
