---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true
    require_chef_omnibus: "11.6.0"
    chef_omnibus_url: https://gist.github.com/hectcastro/6443633/raw/install.sh
    # Requires a patched version of kitchen-vagrant:
    # https://github.com/hectcastro/kitchen-vagrant/compare/hc-cachier
    use_cachier_plugin: true
    customize:
      memory: 512
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "b4e4e31b8e1cd25ea4d3bcd9af94e7322ce1c08645425891574f57ba58f8c516"
    riak_cs:
      package:
        checksum:
          ubuntu:
            precise: "9dac7866c94266c23c9bdff0f94e2c697511ef676372ed1c5b615b2486600b3f"
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: true
    require_chef_omnibus: "11.6.0"
    chef_omnibus_url: https://gist.github.com/hectcastro/6443633/raw/install.sh
    # Requires a patched version of kitchen-vagrant:
    # https://github.com/hectcastro/kitchen-vagrant/compare/hc-cachier
    use_cachier_plugin: true
    customize:
      memory: 512
  run_list:
  - recipe[yum::epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "6": "5bfed85a02df7f297cf20402f147997b06c8ea59dbe860186a54e9dec2dc26e2"
    riak_cs:
      package:
        checksum:
          centos:
            "6": "a742662649876943bbebac6f0af9e887e33a161d70dea040f8a1102c81c99ccc"
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          minor: 4
          incremental: 0
    stanchion:
      package:
        version:
          minor: 4
          incremental: 0
    riak_cs_control:
      package:
        version:
          minor: 0
          incremental: 1
    riak:
      cs_version: "1.4.0"
      package:
        version:
          minor: 4
          incremental: 2
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: default13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          minor: 3
          incremental: 2
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          minor: 4
          incremental: 0
    stanchion:
      package:
        version:
          minor: 4
          incremental: 0
    riak_cs_control:
      package:
        version:
          minor: 0
          incremental: 1
    riak:
      cs_version: "1.4.0"
      package:
        version:
          minor: 4
          incremental: 2
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          minor: 3
          incremental: 3
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
