---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 512

provisioner:
  name: chef_solo
  root_path: /home/vagrant/kitchen

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "f2f5af17cce01a769d31517bbdba5a9e1b99e3581bcc4b33e970dbd0ef4140c6"
    riak_cs:
      package:
        checksum:
          ubuntu:
            trusty: "d8772b5b8ead8e88e70d08c4f63f7231839f349c9b756805522b306a7705f616"
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "f2f5af17cce01a769d31517bbdba5a9e1b99e3581bcc4b33e970dbd0ef4140c6"
    riak_cs:
      package:
        checksum:
          ubuntu:
            precise: "e7bd92dac2a7cfe4a051759df0094d31f0f6029805b4baf0d6ae794acc14f1b7"
- name: debian-7.2.0
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          debian:
            "7": "3bb6bcc409f51e303978fdb72c8605ac87a502e99bb5b7fda5ecd6af9c343d42"
    riak_cs:
      package:
        checksum:
          debian:
            "7": "cd14f18802acaf123f7d5817664dc82bdab214672b7d4f0048cced4d6ec5317c"
- name: centos-6.5
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "6": "5f93a9ed1d7c9326297ebc432d69d1b03e941c057a7cfa37b45138045efdfb4f"
    riak_cs:
      package:
        checksum:
          centos:
            "6": "5561c6452f82d0b3d204e30d1943c017bfe2829036c86e2538f296ce0800dde5"
- name: centos-5.10
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "5": "33c54fd0daccca7005bf65e152b4893d4fecd0cd70becdcde596fb935d93625e"
    riak_cs:
      package:
        checksum:
          centos:
            "5": "c29da52a573182453d0d018c81ff6075f5e4f0a0454fd6110993825b78599761"

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 5
          incremental: 0
    stanchion:
      package:
        version:
          major: 1
          minor: 5
          incremental: 0
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.5.0"
      package:
        version:
          major: 1
          minor: 4
          incremental: 10
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: default14
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 4
          incremental: 5
    stanchion:
      package:
        version:
          major: 1
          minor: 4
          incremental: 3
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.4.5"
      package:
        version:
          major: 1
          minor: 4
          incremental: 10
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: default13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          major: 1
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          major: 1
          minor: 3
          incremental: 2
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          major: 1
          minor: 4
          incremental: 5
    stanchion:
      package:
        version:
          major: 1
          minor: 4
          incremental: 3
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.4.5"
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          major: 1
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          major: 1
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          major: 1
          minor: 3
          incremental: 4
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
