---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box
    require_chef_omnibus: 11.4.4
  run_list:
  - recipe[apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
    require_chef_omnibus: 11.4.4
  run_list:
  - recipe[yum::epel]
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs::control]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak:
      args:
        +S: 1
      config:
        riak_core:
          default_bucket_props: [["__tuple", "allow_mult", true]]
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
    riak-cs:
      args:
        +S: 1
    stanchion:
      args:
        +S: 1
    riak-cs-control:
      args:
        +S: 1
