---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-13.04
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "280c816e5dc4a83e3bc5e82d011fed4b3fb83098b81df2997aa17462261c86e6"
    riak_cs:
      package:
        checksum:
          ubuntu:
            precise: "6d6e8c7e25ebd831a892cc451d38bd00d92b1af9ab0490a061c639d91fa8b2a8"
- name: ubuntu-12.04
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "280c816e5dc4a83e3bc5e82d011fed4b3fb83098b81df2997aa17462261c86e6"
    riak_cs:
      package:
        checksum:
          ubuntu:
            precise: "6d6e8c7e25ebd831a892cc451d38bd00d92b1af9ab0490a061c639d91fa8b2a8"
- name: debian-7.2.0
  attributes:
    riak:
      package:
        checksum:
          debian:
            "7": "ddc35ba5de39bb31a5f4d1b39627ac6b859dc176ff8a6890d95fb32b3f560589"
    riak_cs:
      package:
        checksum:
          debian:
            "7": "2aec430d568b7d180ffecef33219014f838888ba41be96cfbc4d796c06c715c9"
- name: centos-6.5
  attributes:
    riak:
      package:
        checksum:
          centos:
            "6": "2cf9f2481409d2871a6d453a9287f317bd4f5c1cb2e49432f4fee0ac106af56c"
    riak_cs:
      package:
        checksum:
          centos:
            "6": "cfaaea1a59fb4b850f5a54825f996fcee96b554c89569dc00d9d2a7e96516a05"
- name: centos-5.10
  attributes:
    riak:
      package:
        checksum:
          centos:
            "5": "3e6ea55c08c0e0c5d92195955275faed082d0b42fa8bde36e485bbf10b98cae7"
    riak_cs:
      package:
        checksum:
          centos:
            "5": "11c52f02969f8ce6580a7bad55b09fd2c96a0ef28bc8b98b306cbc0d838f759d"

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 4
          incremental: 5
      config:
        riak_cs:
          cs_ip: "__string_0.0.0.0"
          anonymous_user_creation: true
    stanchion:
      package:
        version:
          major: 1
          minor: 4
          incremental: 3
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.4.5"
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: default-ssl
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs-ssl]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 4
          incremental: 5
      config:
        riak_cs:
          cs_ip: "__string_0.0.0.0"
          anonymous_user_creation: true
    stanchion:
      package:
        version:
          major: 1
          minor: 4
          incremental: 3
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
      config:
        riak_cs_control:
          cs_protocol: "__string_https"
    riak:
      cs_version: "1.4.5"
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
    riak_cs_create_admin_user:
      scheme: "https"
      verify_mode: "peer"
      ca_file: "/etc/riak-cs/riak-cs-cert.pem"
- name: default13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          major: 1
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          major: 1
          minor: 3
          incremental: 2
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          major: 1
          minor: 4
          incremental: 5
      config:
        riak_cs:
          cs_ip: "__string_0.0.0.0"
          anonymous_user_creation: true
    stanchion:
      package:
        version:
          major: 1
          minor: 4
          incremental: 3
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.4.5"
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise-ssl
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs-ssl]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          major: 1
          minor: 4
          incremental: 5
      config:
        riak_cs:
          cs_ip: "__string_0.0.0.0"
          anonymous_user_creation: true
    stanchion:
      package:
        version:
          major: 1
          minor: 4
          incremental: 3
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
      config:
        riak_cs_control:
          cs_protocol: "__string_https"
    riak:
      cs_version: "1.4.5"
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
    riak_cs_create_admin_user:
      scheme: "https"
      verify_mode: "peer"
      ca_file: "/etc/riak-cs/riak-cs-cert.pem"
- name: enterprise13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          major: 1
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          major: 1
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          major: 1
          minor: 3
          incremental: 4
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
